spring.application.name=KeyLab
server.port=8080

# Database Supabase - Transaction Pooling IPv4 (SA-EAST-1)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.pwnajivbudcwfcordblx
spring.datasource.password=gx6hsyFOdf0XG2FN
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Connection pool
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=0
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=0
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

spring.security.user.name=admin
spring.security.user.password=admin123
